# numpy functions:


In [1]:
import numpy as np

# arange

In [2]:
# np.arange(start,end,steps(gap))
aray_1d=np.arange(2,25,2)
print(aray_1d)

[ 2  4  6  8 10 12 14 16 18 20 22 24]


# linspace

In [3]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

# reshape

In [4]:
aray_2d=aray_1d.reshape((6,2))
print(aray_2d)


[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]
 [22 24]]


In [5]:
aray_3d=aray_1d.reshape(2,3,2)
print(aray_3d)

[[[ 2  4]
  [ 6  8]
  [10 12]]

 [[14 16]
  [18 20]
  [22 24]]]


In [6]:
nr=np.arange(1,13).reshape(2,6)
print(nr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [7]:
nr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
# flattern
nr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
# ttransprse
aray_2d.transpose()

array([[ 2,  6, 10, 14, 18, 22],
       [ 4,  8, 12, 16, 20, 24]])

In [10]:
aray_2d.transpose()

array([[ 2,  6, 10, 14, 18, 22],
       [ 4,  8, 12, 16, 20, 24]])