In [1]:
import numpy as np

In [ ]:
var=np.random

In [20]:
aray=np.random.ranf(2)
print(aray)

[0.10800987 0.93980022]


In [2]:
arr_1d=np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [3]:
arr_1d.ndim

1

In [4]:
print(arr_1d.dtype)

int32


In [5]:
arr_2d= np.array([[1,2,3],[2,3,4]])
print(arr_2d)

[[1 2 3]
 [2 3 4]]
