In [1]:
import numpy as np

In [7]:
arr_1s= np.array([[1,1,1,1],[1,1,1,1],[1,1,1,1]])
print(arr_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [25]:
mx_1s=np.ones(5)
print(mx_1s)
print(mx_1s.dtype)

[1. 1. 1. 1. 1.]
float64


In [11]:
mx_ones=np.ones((3,4))
print(mx_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
mx_1s=np.ones((3,4),dtype=int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [20]:
mx_zero=np.zeros((4,6),dtype=str)
print(mx_zero)

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [21]:
em_str=''
print(bool(em_str))

False


In [24]:
em_mx = np.empty((3,3),dtype=int)
print(em_mx)

[[       1        1        0]
 [     377      756        0]
 [16777984    32761  6619243]]
